init_conda() {
	# >>> conda initialize >>>
	# !! Contents within this block are managed by 'conda init' !!
	__conda_setup="$($PATEFIANT_ROOT/miniconda3/bin/conda 'shell.bash' 'hook' 2> /dev/null)"
	if [ $? -eq 0 ]; then
			eval "$__conda_setup"
	else
			if [ -f "$PATEFIANT_ROOT/miniconda3/etc/profile.d/conda.sh" ]; then
					. "$PATEFIANT_ROOT/miniconda3/etc/profile.d/conda.sh"
			else
					export PATH="$PATEFIANT_ROOT/miniconda3/bin:$PATH"
			fi
	fi
	unset __conda_setup
	# <<< conda initialize <<<
}

