#!/bin/bash

if [ "$#" -eq 0 ]; then
	$PATEFIANT_ROOT/bin/proot -b $PATEFIANT_ROOT/nix:/nix bash
else
	tmpdir=$(mktemp -d)
	tmpfile=$tmpdir/script.fifo
	mkfifo $tmpfile
	trap "rm -rf $tmpdir" EXIT
	echo ". $HOME/.nix-profile/etc/profile.d/nix.sh && $@" > $tmpfile &
	$PATEFIANT_ROOT/bin/proot -b $PATEFIANT_ROOT/nix:/nix bash $tmpfile
fi
