#!/bin/bash

tmpdir=$(mktemp -d)
tmpfile=$tmpdir/script.fifo
mkfifo $tmpfile
trap "rm -rf $tmpdir" INT TERM EXIT

txtpln='\[\e[0m\]'    # Colour off
txtred='\[\e[0;31m\]' # Red

# we unset LD_LIBRARY_PATH in the rcfile because system paths in
# LD_LIBRARY_PATH takes precedence over paths in /nix/store,
# which would cause linkage issues for nix or programs compiled with nix
init=". $HOME/.bashrc; . $HOME/.nix-profile/etc/profile.d/nix.sh; unset LD_LIBRARY_PATH; PS1=\"(nix)${txtred}\$${txtpln} \"" 

if [ "$#" -eq 0 ]; then
	echo "$init" > $tmpfile &
	$PATEFIANT_ROOT/bin/nix-user-chroot $PATEFIANT_ROOT/nix bash --noprofile --rcfile $tmpfile
else
	echo "$init; $@" > $tmpfile &
	$PATEFIANT_ROOT/bin/nix-user-chroot $PATEFIANT_ROOT/nix bash $tmpfile
fi

