#!/bin/bash
set -o errexit

# Install jar file into common location

if (( $# < 1 )); then
	echo "usage: ${0##*/} <jar_file>"
	exit 1
fi

jarfile=$1; shift
jarbase=${jarfile##*/}
targetfile=$PATEFIANT_JAR_PATH/${jarbase}

cp $jarfile $targetfile

# Create symbolic links if jar file contains versioning
if echo $jarbase | grep -q -E '[-_][0-9]+\.[0-9]+\.jar'; then
	jaralias=$(echo $jarbase | sed -E 's/[-_][0-9]+\.[0-9]+\.jar/.jar/')
	cd $PATEFIANT_JAR_PATH
	ln -sf $jarbase $jaralias
	cd -
fi

