#!/bin/bash
set -o errexit

if (( $# < 1 )); then
	echo "usage: ${0##*/} <jar_file> ..."
	echo
	echo "Available jar files to run: "
	echo
	ls -1 $PATEFIANT_JAR_PATH
	exit 1
fi

jarfile=$1; shift

# append extension if it does not already exist
if [[ ${jarfile##*.} != "jar" ]]; then
	jarfile=${jarfile}.jar
fi

java -jar $PATEFIANT_JAR_PATH/$jarfile "$@"
